spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&socketTimeout=1800000&useSSL=true
    username: root
    password: lijianjun
    driverClassName: com.mysql.jdbc.Driver

#  data:
#    mongodb:
#      url: mongodb://test:123@localhost:27017/test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#配置日志
logging:
  #配置日志文件路径
  config: classpath:logback-spring-dev.xml