#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3308/test?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&socketTimeout=1800000&useSSL=true
#    username: root
#    password: lijianjun
#    driverClassName: com.mysql.jdbc.Driver
#    connectionInitSqls:
sharding:
  jdbc:
    datasource:
      names: default
      default:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3308/test?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&socketTimeout=1800000&useSSL=true
        username: root
        password: lijianjun
        connection-Init-Sqls:
           - "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
    config:
      sharding:
        tables:
          t_comment:
            actual-data-nodes:  default.t_comment_${0..99}
            table-strategy:
              inline:
                sharding-column: target_id
                algorithm-expression: t_comment_${Math.abs(target_id.hashCode()) % 100}
          t_praise:
            actual-data-nodes: default.t_praise_${0..99}
            table-strategy:
              inline:
                sharding-column: target_id
                algorithm-expression: t_praise_${Math.abs(target_id.hashCode()) % 100}
          soc_notify_user_message:
            actual-data-nodes: default.soc_notify_user_message_${0..99}
            table-strategy:
              inline:
                sharding-column: notify_aid
                algorithm-expression: soc_notify_user_message_${Math.abs(notify_aid.hashCode()) % 100}

#  data:
#    mongodb:
#      url: mongodb://test:123@localhost:27017/test

#      connection:
 #        CharSet: utf8mb4

cache:
  supported: true
  
  servers: 127.0.0.1;
#    -172.16.16.101
#    -172.16.16.102
#    -172.16.16.103
  port: 11211
  
  pool:
    name: sms_cache
    maxConnections: 50
    socketTimeout: 2000
    socketConnectTimeout: 60000
    timeout: 600000
    prefix: sms
    binaryProtocal: true
    aliveCheck: false
    failback: true
    failover: true
    opTimeout: 30000

#配置日志
logging:
  #配置日志文件路径
  config: classpath:logback-spring-dev.xml