#web
server:
  port: 8085

#
spring:
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/msm?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&socketTimeout=1800000&useSSL=false
    username: db_user
    password: ENC(d2NjX2NyeXB0ATQxNDU1MzVGNDM0MjQzOzMzMzM0NDMyMzM0MzMwNDY0MzM3MzUzMjQxMzczNTQyNDUzMTMyNDQ0NjQ2MzkzNjQxMzAzOTMyMzYzODM0Mzc7OzM1MzAzMDMwMzA7NzM5NkE3NkQyODQ4RkY5RjQ1MDYxQTg0QzczMTlGMjc7RTU2ODA0NTgxMjJGNzQzNDs,d2NjX2NyeXB0ATQxNDU1MzVGNDM0MjQzOzQyNDQ0MzMzMzkzMDMxNDE0NDMyNDUzNDMyMzYzMzM2MzIzMDM5NDQzODM0NDUzMjM4NDQzODM2MzczMjM1MzUzMDM1MzM0MzMwMzUzMTQyMzUzMzMyNDUzMjM3MzAzNDM0NDYzMDMwMzQ0MTQ0NDIzMjQzMzQ0MzQ2MzU0NTMzMzI0NTM0Mzg0MzM2NDE0NTM3NDYzODQxNDYzMDQ1MzU0MjM0MzUzMDMwMzczMzQ0Mzg0NjQxNDMzNzM5NDU0MTszMTM1MzAzMTM1MzczNDMyMzgzMzM5MzQzMjszNTMwMzAzMDMwO0RBOUE1OEY2RDY5Q0Q3MjlEOTRCMzYyNDk0NDNCOTQ4Ow)
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
   
#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: error
    org.springfromework.web: error
    org.hibernate: error
 
  file: ../logs/msm.log
