spring:
  application:
    name: cdmi-dws-service
  cache:
    cache-name: msm-cache
    guava.spec: maximumSize=500,expireAfterWrite=10m
    encache:
      config: 
  profiles:
    active: @profileActive@
    
 # redis:
 #   cluster:
 #     nodes: 
 #       - localhost:6379
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: 
#    ssl: false
#    timeout: 3000
#    pool:
 #     max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0

MessageTemplates:
  templates:
    default: 你的验证码为：
    