spring:
  application:
    name: cdmi-dws-service
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: pw.cdmi.config.MySQL5InnoDBDialectUtf8mb4
    datasource:
      druid:
        connection-init-sqls: ["SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"]
    show-sql: true
    hibernate:
      ddl-auto: update
MessageTemplates:
  templates:
    default: 你的验证码为：
    