#web
server:
  port: 8085

#
spring:
  datasource:
    url: jdbc::mysql://192.168.2.63:8635/msm?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&socketTimeout=1800000&useSSL=false
    username: cloudapp_user
    password: 6;aVhFRF8<ms
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
   
#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: error
    org.springfromework.web: error
    org.hibernate: error
 
  file: ../logs/msm.log
