spring:
  application:
    name: cdmi-demo-api
  datasource:
    url: jdbc:mysql://localhost:3308/test?useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: root
    password: lijianjun
    driverClassName: com.mysql.jdbc.Driver
  
  
  data:
    mongodb:
      url: mongodb://test:123@localhost:27017/test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
   
   
   
  
   #配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
 
  file: log\myspringboot.log
