#web
server:
  port: 8085

#
spring:
  datasource:
    url: jdbc:mysql://172.16.0.5:8635/msm?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&socketTimeout=1800000&useSSL=false
    username: cloud_user
    password: 6_aVhFRF8%ms
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
   
#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: error
    org.springfromework.web: error
    org.hibernate: error
 
  file: ../logs/msm.log
